---
- hosts: dc1
  user: root
  sudo: True
  tasks:

  - include: tasks/dependencies.yml
  - include: tasks/repositories.yml
  - include: tasks/java-install.yml
  - include: tasks/dse-install.yml
  - include: tasks/topology.yml
  - include: tasks/start-dse.yml


- hosts: dc2
  user: root
  sudo: True
  tasks:

  - include: tasks/dependencies.yml
  - include: tasks/repositories.yml
  - include: tasks/java-install.yml
  - include: tasks/dse-spark-install.yml
  - include: tasks/topology.yml
  - include: tasks/start-dse.yml
