---
- hosts: all
  user: root
  sudo: True
  tasks:

  - include: tasks/dependencies.yml
  - include: tasks/repositories.yml
  - include: tasks/java-install.yml
  - include: tasks/dse-solr-install.yml
  - include: tasks/start-dse.yml
