- name: installing some dependencies
  yum: name={{ item }} state=installed
  with_items:
  - jna
  - libselinux-python

- file: dest=/opt state=directory
- name: copying jdk and jna file
  copy: src={{ item }} dest=/opt/ owner=root group=root mode="u=rwx,g=rx,o=rx"
  with_fileglob:
  - /Users/phanindra/Development/dse-ansible/files/jdk-8u65-linux-x64.rpm
  - /Users/phanindra/Development/dse-ansible/files/jna-3.4.0-4.el5.x86_64.rpm

- name: install java rpm from a local file
  yum: name={{ item }} state=present
  with_items:
  - /opt/jdk-8u65-linux-x64.rpm
  - /opt/jna-3.4.0-4.el5.x86_64.rpm

- name: Install OracleJDK to Alternatives
  #alternatives: name=java path=/usr/java/default/bin/java
  shell: /usr/sbin/alternatives --install /usr/bin/java java /usr/java/default/bin/java 20000 && touch /root/.installalternatives
  args:
    creates: /root/.installalternatives

- name: Set OracleJDK to default
  shell: /usr/sbin/alternatives --set java /usr/java/default/bin/java && touch /root/.setalternatives
  args:
    creates: /root/.setalternatives
