- include_vars: '/root/dse-deployer/defaults/main.yml'
- name: installing datastax enterprise
  yum: name=dse-full-4.5.8-1 state=installed
  register: dse

- name: configuring datastax enterprise
  template: src=templates/cassandra.yaml.j2 dest=/etc/dse/cassandra/cassandra.yaml
