- name: installing datastax enterprise
  yum: name=dse-full-4.8.3-1 state=installed
  register: dse

- name: configuring datastax enterprise
  template: src={{item.src}} dest={{item.dest}}
  with_items:
      - { src: 'templates/cassandra.yaml.j2', dest: '/etc/dse/cassandra/cassandra.yaml' }
      - { src: 'templates/cassandra-env.sh.j2', dest: '/etc/dse/cassandra/cassandra-env.sh' }
      - { src: 'templates/dse.j2', dest: '/etc/default/dse' }
      - { src: 'templates/dse.yaml.j2', dest: '/etc/dse/dse.yaml' }

- name: Check the datastax agent version
  shell: rpm -qa | grep datastax-agent
  register: datastaxagent_version
  args:
    creates: /root/.deleted_datastax_agent


- name: Uninstall Latest version of datastax agent
  shell: rpm -e --nodeps {{ item }} && touch /root/.deleted_datastax_agent
  with_items: datastaxagent_version.stdout_lines
  args:
    creates: /root/.deleted_datastax_agent


- name: installing datastax agent
  yum: name='{{ dse_config.datastax_agent_version }}' state=installed
