- name: Check that the repo file exists
  stat: path=/etc/yum.repos.d/datastax.repo
  register: repo_file

- name: Adding Datastax Repo
  copy: src=files/datastax.repo dest=/etc/yum.repos.d/datastax.repo owner=root group=root
  when: repo_file.stat.exists == False
